FIELDS = {
    'id': None,
    'raceid': None,
    'racetype': None,
    'racetypeid': None,
    'ballotorder': None,
    'candidateid': None,
    'description': None,
    'delegatecount': None,
    'electiondate': None,
    'electtotal': None,
    'electwon': None,
    'fipscode': None,
    'first': None,
    'incumbent': None,
    'initialization_data': None,
    'is_ballot_measure': None,
    'last': None,
    'lastupdated': None,
    'level': None,
    'national': None,
    'officeid': None,
    'officename': None,
    'party': None,
    'polid': None,
    'polnum': None,
    'precinctsreporting': None,
    'precinctsreportingpct': None,
    'precinctstotal': None,
    'reportingunitid': None,
    'reportingunitname': None,
    'runoff': None,
    'seatname': None,
    'seatnum': None,
    'statename': None,
    'statepostal': None,
    'test': None,
    'uncontested': None,
    'candidate_unique_id': None,
    'votecount': None,
    'votepct': None,
    'winner':None
}

FIELDNAMES = FIELDS.keys()
