FIELDS = {
    'id': None,
    'raceid': None,
    'racetype': None,
    'racetypeid': None,
    'ballotorder': None,
    'candidateid': None,
    'description': None,
    'delegatecount': None,
    'electiondate': None,
    'electtotal': None,
    'electwon': None,
    'fipscode': None,
    'first': None,
    'incumbent': None,
    'initialization_data': None,
    'is_ballot_position': None,
    'last': None,
    'lastupdated': None,
    'level': None,
    'national': None,
    'officeid': None,
    'officename': None,
    'party': None,
    'polid': None,
    'polnum': None,
    'precinctsreporting': None,
    'precinctsreportingpct': None,
    'precinctstotal': None,
    'reportingunitid': None,
    'reportingunitname': None,
    'runoff': None,
    'seatname': None,
    'seatnum': None,
    'statename': None,
    'statepostal': None,
    'test': None,
    'uncontested': None,
    'candidate_unique_id': None,
    'votecount': None,
    'votepct': None,
    'winner':None
}

FIELDNAMES = ('id','raceid','racetype','racetypeid','ballotorder','candidateid','description',
                'delegatecount','electiondate','electtotal','electwon','fipscode','first',
                'incumbent','initialization_data','is_ballot_position','last','lastupdated',
                'level','national','officeid','officename','party','polid','polnum',
                'precinctsreporting','precinctsreportingpct','precinctstotal','reportingunitid',
                'reportingunitname','runoff','seatname','seatnum','statename','statepostal',
                'test','uncontested','candidate_unique_id','votecount','votepct','winner')
